version: "3.8"
services:
  application:
    build: .
    restart: on-failure
    ports:
      - $SPRING_PORT:$SPRING_PORT
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      WAIT_HOSTS: db:$DB_PORT
  db:
    image: mysql:latest
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${DB_PORT}
    expose:
      - $DB_PORT
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:


