spring:
  datasource:
    url: jdbc:mysql://${SPRING_DATABASE_HOST}:${DB_PORT}/${DATABASE}?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      platform: mysql
  servlet:
    multipart:
      maxFileSize: 1000000MB
      maxRequestSize: 1000000MB
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        generate-ddl: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        
server:
  port: ${SPRING_PORT}